// Code generated by "stringer -type=API,ID -linecomment -output=filesystem_string.go"; DO NOT EDIT.

package filesystem

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[apiStart-0]
	_ = x[Fuse-1]
	_ = x[Plan9Protocol-2]
	_ = x[apiEnd-3]
}

const _API_name = "apiStartFuse9PapiEnd"

var _API_index = [...]uint8{0, 8, 12, 14, 20}

func (i API) String() string {
	if i >= API(len(_API_index)-1) {
		return "API(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _API_name[_API_index[i]:_API_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[idStart-0]
	_ = x[IPFS-1]
	_ = x[IPNS-2]
	_ = x[Files-3]
	_ = x[PinFS-4]
	_ = x[KeyFS-5]
	_ = x[MFS-6]
	_ = x[idEnd-7]
}

const _ID_name = "idStartIPFSIPNSFilesPinFSKeyFSMFSidEnd"

var _ID_index = [...]uint8{0, 7, 11, 15, 20, 25, 30, 33, 38}

func (i ID) String() string {
	if i >= ID(len(_ID_index)-1) {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[i]:_ID_index[i+1]]
}
