// Code generated by "stringer -type=API,ID -linecomment -output standards_string.go"; DO NOT EDIT.

package filesystem

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Fuse-2147483646]
	_ = x[Plan9Protocol-2147483645]
	_ = x[PathProtocol-47]
}

const (
	_API_name_0 = "path"
	_API_name_1 = "9pfuse"
)

var (
	_API_index_1 = [...]uint8{0, 2, 6}
)

func (i API) String() string {
	switch {
	case i == 47:
		return _API_name_0
	case 2147483645 <= i && i <= 2147483646:
		i -= 2147483645
		return _API_name_1[_API_index_1[i]:_API_index_1[i+1]]
	default:
		return "API(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IPFS-4]
	_ = x[IPNS-5]
	_ = x[Files-6]
	_ = x[PinFS-7]
	_ = x[KeyFS-8]
}

const _ID_name = "ipfsipnsfilepinfskeyfs"

var _ID_index = [...]uint8{0, 4, 8, 12, 17, 22}

func (i ID) String() string {
	i -= 4
	if i < 0 || i >= ID(len(_ID_index)-1) {
		return "ID(" + strconv.FormatInt(int64(i+4), 10) + ")"
	}
	return _ID_name[_ID_index[i]:_ID_index[i+1]]
}
