// Code generated by "stringer -type=API,ID -linecomment -output=id_string.go"; DO NOT EDIT.

package filesystem

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[apiStart-0]
	_ = x[Fuse-1]
	_ = x[Plan9Protocol-2]
	_ = x[apiEnd-3]
}

const _API_name = "Fuse9P"

var _API_index = [...]uint8{0, 0, 4, 6, 6}

func (i API) String() string {
	if i >= API(len(_API_index)-1) {
		return "API(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _API_name[_API_index[i]:_API_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[idStart-0]
	_ = x[IPFSPins-1]
	_ = x[IPFS-2]
	_ = x[IPFSKeys-3]
	_ = x[IPNS-4]
	_ = x[IPFSFiles-5]
	_ = x[MFS-6]
	_ = x[idEnd-7]
}

const _ID_name = "PinFSIPFSKeyFSIPNSFilesMFS"

var _ID_index = [...]uint8{0, 0, 5, 9, 14, 18, 23, 26, 26}

func (i ID) String() string {
	if i >= ID(len(_ID_index)-1) {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[i]:_ID_index[i+1]]
}
