// Code generated by "stringer -type=tableColumn -linecomment"; DO NOT EDIT.

package formats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[thBinding-0]
	_ = x[thError-1]
	_ = x[thEnd-2]
}

const _tableColumn_name = "BindingErrorEnd"

var _tableColumn_index = [...]uint8{0, 7, 12, 15}

func (i tableColumn) String() string {
	if i < 0 || i >= tableColumn(len(_tableColumn_index)-1) {
		return "tableColumn(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tableColumn_name[_tableColumn_index[i]:_tableColumn_index[i+1]]
}
