name: "Release"
description: "Publish a GitHub release."
runs:
  using: "composite"
  steps:
    - name: Build
      shell: pwsh
      run: |
        mkdir build
        go build -o .${{ matrix.pathdelm }}build .${{ matrix.pathdelm }}cmd${{ matrix.pathdelm }}fs

    - name: Archive (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        mkdir release
        Compress-Archive -Path '.\build\*' -DestinationPath '.\release\go-fs-windows-amd64.zip'

    - name: 'Archive (*nix)'
      if: runner.os != 'Windows'
      shell: bash
      run: |
        mkdir release
        pushd build
        tar czf ../release/go-fs-linux-amd64.tar.gz *
        popd

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
        gh release create --generate-notes --prerelease --title "testing CI" v0.0.0 ./release
