name: "Prerelease"
description: "Publish a GitHub (pre-)release"
inputs:
  github-token:
    description: "Token used to publish releases"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      # TODO: --notes-file something.md; install instructions + mhash of release dir
      # TODO: some kind of coordination between artifact / directory names. inputs<=>outputs?
      run: |
        pushd artifact
        gh release create --prerelease --generate-notes --title "testing CI" prerelease *
        popd
