// Code generated by "stringer --type=another"; DO NOT EDIT.

package testcmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[anotherStart-0]
	_ = x[another1-1]
	_ = x[another2-2]
	_ = x[anotherEnd-3]
}

const _another_name = "anotherStartanother1another2anotherEnd"

var _another_index = [...]uint8{0, 12, 20, 28, 38}

func (i another) String() string {
	if i >= another(len(_another_index)-1) {
		return "another(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _another_name[_another_index[i]:_another_index[i+1]]
}
