// Code generated by "stringer --type=customID"; DO NOT EDIT.

package testcmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[thingStart-0]
	_ = x[IPFS-1]
	_ = x[IPNS-2]
	_ = x[MFS-3]
	_ = x[thingEnd-4]
}

const _customID_name = "thingStartIPFSIPNSMFSthingEnd"

var _customID_index = [...]uint8{0, 10, 14, 18, 21, 29}

func (i customID) String() string {
	if i >= customID(len(_customID_index)-1) {
		return "customID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _customID_name[_customID_index[i]:_customID_index[i+1]]
}
