// Code generated by "stringer --type=fsID"; DO NOT EDIT.

package testcmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fsidStart-0]
	_ = x[fuse-1]
	_ = x[p9-2]
	_ = x[fsidEnd-3]
}

const _fsID_name = "fsidStartfusep9fsidEnd"

var _fsID_index = [...]uint8{0, 9, 13, 15, 22}

func (i fsID) String() string {
	if i >= fsID(len(_fsID_index)-1) {
		return "fsID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _fsID_name[_fsID_index[i]:_fsID_index[i+1]]
}
