name: "Setup FUSE-T"
description: "Installs FUSE-T development dependencies and links as osxfuse"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        brew tap macos-fuse-t/homebrew-cask
        brew install fuse-t
