name: "Setup WinFSP"
description: "Installs WinFSP development dependencies."
runs:
  using: "composite"
  steps:
  - name: Install winfsp
    shell: pwsh
    run: |
      $releases = Invoke-WebRequest https://api.github.com/repos/winfsp/winfsp/releases | `
        ConvertFrom-Json
       $asseturi = $releases[0].assets.browser_download_url | `
          Where-Object { $_ -match "winfsp-.*\.msi" }
      Invoke-WebRequest -Uri $asseturi -Out winfsp.msi
      Start-Process -NoNewWindow -Wait msiexec "/i winfsp.msi /qn INSTALLLEVEL=1000"
