// Code generated by "stringer -type=tableColumn -linecomment -output formatter_string.go"; DO NOT EDIT.

package fscmds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[thHAPI-0]
	_ = x[thNAPI-1]
	_ = x[thBinding-2]
	_ = x[thExtra-3]
	_ = x[tableWidth-4]
}

const _tableColumn_name = "Host APINode APIBindingOptionstableWidth"

var _tableColumn_index = [...]uint8{0, 8, 16, 23, 30, 40}

func (i tableColumn) String() string {
	if i < 0 || i >= tableColumn(len(_tableColumn_index)-1) {
		return "tableColumn(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tableColumn_name[_tableColumn_index[i]:_tableColumn_index[i+1]]
}
