// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Other-0]
	_ = x[InvalidItem-1]
	_ = x[InvalidOperation-2]
	_ = x[Permission-3]
	_ = x[IO-4]
	_ = x[Exist-5]
	_ = x[NotExist-6]
	_ = x[IsDir-7]
	_ = x[NotDir-8]
	_ = x[NotEmpty-9]
	_ = x[ReadOnly-10]
}

const _Kind_name = "OtherInvalidItemInvalidOperationPermissionIOExistNotExistIsDirNotDirNotEmptyReadOnly"

var _Kind_index = [...]uint8{0, 5, 16, 32, 42, 44, 49, 57, 62, 68, 76, 84}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
