// Code generated by "stringer -type=StopReason -linecomment"; DO NOT EDIT.

package daemon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RequestCanceled-1]
	_ = x[Idle-2]
	_ = x[StopRequested-3]
}

const _StopReason_name = "Request was canceledService was idleStop was requested"

var _StopReason_index = [...]uint8{0, 20, 36, 54}

func (i StopReason) String() string {
	i -= 1
	if i >= StopReason(len(_StopReason_index)-1) {
		return "StopReason(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _StopReason_name[_StopReason_index[i]:_StopReason_index[i+1]]
}
