name: Actions
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  Test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/test
  Build:
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/build
      - uses: ./.github/actions/archive
  Release:
    if: github.ref == 'refs/heads/master'
    needs: [Test, Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: ./.github/actions/latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
