name: Tests
on:
  push:
    branches:
      - master
      - j/mount
  pull_request:
jobs:
  test:
    strategy:
        matrix:
          os: [windows-latest, macos-latest, ubuntu-latest]
          include:
            - os: windows-latest
              pathdelm: \
              cpath: C:\Program Files (x86)\WinFsp\inc\fuse
            - os: macos-latest
              pathdelm: /
            - os: macos-latest
              pathdelm: /
    runs-on: ${{ matrix.os }}
    env:
      CPATH: ${{ matrix.cpath }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test
        uses: ./.github/actions/test
